# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetsenseiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Google-Mobile-Ads-SDK'
pod 'Smart-Display-SDK'
pod 'AdformAdvertising'
pod 'GoogleMobileAdsMediationChartboost'
pod 'GoogleMobileAdsMediationTapjoy'
pod 'GoogleMobileAdsMediationChartboost'
pod 'GoogleMobileAdsMediationAdColony'
pod 'GoogleMobileAdsMediationAppLovin'
pod 'GoogleMobileAdsMediationFyber'
pod 'GoogleMobileAdsMediationInMobi'
pod 'GoogleMobileAdsMediationIronSource'
pod 'GoogleMobileAdsMediationMyTarget'
pod 'GoogleMobileAdsMediationTapjoy'
pod 'GoogleMobileAdsMediationUnity'
pod 'GoogleMobileAdsMediationFacebook'
pod 'GoogleMobileAdsMediationVungle'
  # Pods for NetsenseiOS

end
